const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const { v4: uuidv4 } = require('uuid');
const { uploadBuffer } = require('./firebaseStorage');

const fetchRemoteBuffer = async (url) => {
  if (!url) {
    return null;
  }

  const response = await fetch(url);

  if (!response.ok) {
    return null;
  }

  const arrayBuffer = await response.arrayBuffer();
  return Buffer.from(arrayBuffer);
};

const buildPdfBuffer = async ({ title, donorName, ngoName, bodyLines, certificateId, qrBuffer, logoBuffer }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fillColor('#1A1A2E').fontSize(28).font('Helvetica-Bold').text('Celebrate With Purpose', {
      align: 'center',
    });
    doc.moveDown(0.3);
    doc.fillColor('#FF6B35').fontSize(16).text(title, { align: 'center' });
    doc.moveDown(1.25);

    if (logoBuffer) {
      try {
        doc.image(logoBuffer, doc.page.width / 2 - 36, 120, {
          fit: [72, 72],
          align: 'center',
        });
        doc.moveDown(3.4);
      } catch (error) {
        doc.moveDown(1.2);
      }
    }

    doc.fillColor('#1A1A2E').fontSize(22).font('Helvetica-Bold').text('Certificate of Appreciation', {
      align: 'center',
    });
    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica').fillColor('#3B3B4F');
    doc.text(`This certifies that ${donorName}`, { align: 'center' });
    doc.moveDown(0.2);
    doc.font('Helvetica-Bold').fontSize(18).fillColor('#1A1A2E').text(donorName, { align: 'center' });
    doc.moveDown(0.8);

    doc.font('Helvetica').fontSize(13).fillColor('#3B3B4F');
    bodyLines.forEach((line) => {
      doc.text(line, { align: 'center' });
      doc.moveDown(0.35);
    });

    doc.moveDown(1.1);
    doc.fillColor('#FF6B35').font('Helvetica-Bold').fontSize(16).text('Thank you for your kindness', {
      align: 'center',
    });

    doc.moveDown(1.6);
    doc.font('Helvetica').fontSize(11).fillColor('#5D5D72');
    doc.text(`Beneficiary NGO: ${ngoName}`, { align: 'left' });
    doc.text(`Certificate ID: ${certificateId}`, { align: 'left' });
    doc.text('Generated by Celebrate With Purpose', { align: 'left' });

    doc.image(qrBuffer, doc.page.width - 132, doc.page.height - 180, { fit: [84, 84] });
    doc.fontSize(10).text('Scan to verify', doc.page.width - 132, doc.page.height - 86, {
      width: 84,
      align: 'center',
    });

    doc.end();
  });

const generateCertificate = async ({
  type,
  donorUid,
  donorName,
  ngo,
  amount,
  itemsDelivered,
  referenceValue,
  issuedAt,
  verificationBaseUrl,
}) => {
  const certificateId = uuidv4();
  const verifyUrl = `${verificationBaseUrl.replace(/\/$/, '')}/verify/${certificateId}`;
  const qrBuffer = await QRCode.toBuffer(verifyUrl, {
    margin: 1,
    color: {
      dark: '#1A1A2E',
      light: '#F8F6F0',
    },
  });
  const logoBuffer = await fetchRemoteBuffer(ngo.logoUrl);

  const bodyLines =
    type === 'donation'
      ? [
          `for donating Rs. ${amount} to support the residents of ${ngo.name}.`,
          `Transaction reference: ${referenceValue}`,
          `Date: ${new Date(issuedAt).toLocaleDateString('en-IN')}`,
        ]
      : [
          `for delivering ${itemsDelivered} to support the residents of ${ngo.name}.`,
          `Delivery reference: ${referenceValue}`,
          `Date: ${new Date(issuedAt).toLocaleDateString('en-IN')}`,
        ];

  const pdfBuffer = await buildPdfBuffer({
    title: type === 'donation' ? 'Verified Donation' : 'Verified Delivery',
    donorName,
    ngoName: ngo.name,
    bodyLines,
    certificateId,
    qrBuffer,
    logoBuffer,
  });

  const upload = await uploadBuffer({
    buffer: pdfBuffer,
    destination: `certificates/${donorUid}/${certificateId}.pdf`,
    mimetype: 'application/pdf',
    metadata: {
      certificateId,
      donorUid,
      ngoId: ngo.ngoId,
      type,
    },
  });

  return {
    certificateId,
    certificateUrl: upload.url,
    certificatePath: upload.path,
    verifyUrl,
  };
};

module.exports = {
  generateCertificate,
};

